-- =============================================================================
-- Player 360 Demo — Step 1: Database, schemas, and tables
-- Run as SYSADMIN or ACCOUNTADMIN.
-- To use a different warehouse, edit the USE WAREHOUSE line.
-- =============================================================================

USE WAREHOUSE COMPUTE_WH;   -- <-- change to your warehouse

CREATE DATABASE IF NOT EXISTS PLAYER_360;
CREATE SCHEMA IF NOT EXISTS PLAYER_360.RAW;
CREATE SCHEMA IF NOT EXISTS PLAYER_360.ANALYTIC;
CREATE SCHEMA IF NOT EXISTS PLAYER_360.APP;

-- ========================================== RAW schema
USE SCHEMA PLAYER_360.RAW;

CREATE OR REPLACE TABLE USERS (
    USER_ID         NUMBER(5,0),
    ALIAS           VARCHAR,
    FIRST_NAME      VARCHAR,
    LAST_NAME       VARCHAR,
    GENDER          VARCHAR,
    EMAIL           VARCHAR,
    LOCATION        VARCHAR,
    ACCOUNT_CREATION DATE,
    CONSENT         BOOLEAN,
    PHOTO_URL       VARCHAR,
    BIRTHDATE       DATE
);

CREATE OR REPLACE TABLE SESSIONS (
    USER_ID                  NUMBER(5,0),
    SESSION_ID               NUMBER(12,0),
    LOG_IN                   TIMESTAMP_NTZ,
    LOG_OUT                  TIMESTAMP_NTZ,
    SESSION_DURATION_MINUTES NUMBER(3,1),
    DEVICE_TYPE              VARCHAR
);

CREATE OR REPLACE TABLE PURCHASES (
    USER_ID                NUMBER(5,0),
    PURCHASE_ID            NUMBER(10,0),
    PURCHASE_AMOUNT        NUMBER(4,2),
    PURCHASE_TYPE          VARCHAR,
    TIMESTAMP_OF_PURCHASE  TIMESTAMP_NTZ,
    AD_INTERACTION_ID      NUMBER(9,0),
    AD_TYPE                VARCHAR,
    AD_ENGAGEMENT_TIME     NUMBER(2,0),
    AD_CONVERSION          BOOLEAN
);

CREATE OR REPLACE TABLE GAME_EVENTS (
    ASSISTS           NUMBER(2,0),
    BOOSTS            NUMBER(2,0),
    DAMAGE_DEALT      NUMBER(6,2),
    DISTANCE_TRAVELED NUMBER(5,2),
    GROUP_ID          VARCHAR,
    HEADSHOTS         NUMBER(2,0),
    HEALS             NUMBER(2,0),
    KILLS             NUMBER(2,0),
    MATCH_ID          VARCHAR,
    SESSION_ID        VARCHAR,
    USER_ID           NUMBER(5,0),
    WEAPONS_ACQUIRED  NUMBER(1,0)
);

CREATE OR REPLACE TABLE ACHIEVEMENTS (
    USER_ID                NUMBER(5,0),
    VICTORY_ROYALE         BOOLEAN,
    ELIMINATION_MILESTONES BOOLEAN,
    SURVIVAL_ACHIEVEMENTS  BOOLEAN,
    BUILDING_RESOURCES     BOOLEAN,
    EXPLORATION_TRAVEL     BOOLEAN,
    WEAPON_USAGE           BOOLEAN,
    ASSIST_TEAMMATES       BOOLEAN,
    EVENT_CHALLENGES       BOOLEAN,
    CREATIVE_MODE          BOOLEAN,
    SOCIAL_ACHIEVEMENTS    BOOLEAN
);

CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    CASE_ID            NUMBER(5,0),
    USER_ID            NUMBER(5,0),
    CATEGORY           VARCHAR,
    CASE_DESCRIPTION   VARCHAR,
    SENTIMENT_ANALYSIS NUMBER(10,9),
    DATE_CREATED       TIMESTAMP_NTZ
);

-- ========================================== ANALYTIC schema
USE SCHEMA PLAYER_360.ANALYTIC;

CREATE OR REPLACE TABLE DAILY_ACTIVE_USERS (
    ACTIVE_DATE       DATE,
    ACTIVE_USER_COUNT NUMBER(38,0)
);

CREATE OR REPLACE TABLE MONTHLY_ACTIVE_USERS (
    ACTIVE_MONTH       DATE,
    ACTIVE_USER_COUNT  NUMBER(38,0)
);

CREATE OR REPLACE TABLE POINTS_MAPPING_TABLE (
    EVENT  VARCHAR,
    POINTS FLOAT
);

CREATE OR REPLACE TABLE RANKING_MAPPING_TABLE (
    RANK_NAME   VARCHAR,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT
);
